#!/bin/sh
rsync -av ./nomutilisateur@nomDomaine:/~nomDuSite --include=public/build --include=public/.htacess --exclude-from=.ignire --exclude=".*"
ssh nomutilisateur@nomDomaine 'cd ~/monsite && php-7.3 bin/console cache:clear'